# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'QRCodeReaderViewController' do


pod 'AFNetworking', '~> 2.2'
pod 'JPSVolumeButtonHandler'

end

target 'QRCodeReaderViewControllerTests' do

end

