# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

pod 'AFNetworking', '~> 2.2'
pod 'ZXingObjC', '~> 3.0'

target 'QRCodeReaderViewController' do

end

target 'QRCodeReaderViewControllerTests' do

end

